config/routes.rb
Koreyomo::Application.routes.draw do
  get "home/index"
  devise_for :users

  # twitter-auth
  get '/auth/:provider/callback', :to => 'sessions#callback'
  post '/auth/:provider/callback', :to => 'sessions#callback'
  get '/logout' => 'sessions#destroy', :as => :logout
  get '/auth/failure' => 'sessions#failure'

  resources :tasks do
    collection do
      get :done
    end

    member do
      post :increase_point
    end
  end
  resources :books

  root 'home#index'
end

app/models/book.rb
class Book < ActiveRecord::Base
  validates_presence_of :title, :isbn, :author
  belongs_to :user
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  has_many :task_points

  scope :wip, -> { where(state: 'wip') }
  scope :ready, -> { where(state: 'ready') }
  scope :done, -> { where(state: 'done') }

  scope :finished_in_week, -> { where(finished_at: 7.days.ago..Time.current) }
  scope :finished_in_30_days, -> { where(finished_at: 30.days.ago..Time.current) }

  STATE_NAME = {
    icebox: '積み',
    ready: '準備OK',
    wip: '作業中',
    done: '完了'
  }

  # State Machine
  state_machine :state, initial: :icebox do
    state :icebox
    state :ready
    state :wip
    state :done

    after_transition ready: :wip do |task|
      task.touch(:started_at)
    end
  end

  def state_name
    STATE_NAME[state.to_sym]
  end

  def increase_point(point)
    self.task_points << TaskPoint.new(point: point)
  end

  def progress_point
    task_points.map(&:point).sum
  end

  def self.periodic_done(period)
    #TODO Must Refactor
    if period.blank?
      finished_in_week
    elsif period == 'all'
      done
    elsif  period == 'week'
      finished_in_week
    elsif  period == 'month'
      finished_in_30_days
    end
  end
end

app/models/task_point.rb
class TaskPoint < ActiveRecord::Base
  validates_presence_of :point
  belongs_to :task
end

app/models/user.rb
class User < ActiveRecord::Base
  FAKE_ADDRESS = "fake@fake.jp"
  FAKE_PASSWORD = "abcdefg"
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      user.screen_name = auth['info']['nickname']
      user.name = auth['info']['name']

      user.email = FAKE_ADDRESS
      user.password = FAKE_PASSWORD + rand(100000).round.to_s
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :set_user
  protect_from_forgery with: :exception

  def set_user
    @current_user = User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  protect_from_forgery

  def login_required
    if session[:user_id]
      @current_user = User.find(session[:user_id])
    else
      redirect_to root_path
    end
  end

  helper_method :current_user

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :set_user

  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render action: 'show', status: :created, location: @book }
      else
        format.html { render action: 'new' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params[:book]
    end

  def set_user
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @tasks_ready = Task.ready
    @tasks_wip = Task.wip
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def callback
    auth = request.env['omniauth.auth']
    user = User.find_by_provider_and_uid(auth['provider'], auth['uid']) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  def failure
    redirect_to :destroy
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :increase_point]
  before_action :set_user

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  def increase_point
    @task.increase_point(params[:point])
    render :show, notice: '進捗を登録しました'
  end

  def done
    @tasks = Task.periodic_done(params[:period])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render action: 'show', status: :created, location: @task }
      else
        format.html { render action: 'new' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :size)
    end

  def set_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/base_helper.rb
module BaseHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/books/_form.html.slim
= form_for(@book) do |f|
  - if @book.errors.any?
    div id="error_explanation"
      h2 = pluralize(@book.errors.count, "error")  prohibited this book from being saved:

      ul
        - @book.errors.full_messages.each do |msg|
          li = msg


  div class="actions"
    = f.submit

app/views/books/edit.html.slim
h1.page-header 書籍情報の編集

= render 'form'

= link_to 'Show', @book
'|
= link_to '一覧に戻る', books_path

app/views/books/index.html.slim
h1.page-header 書籍一覧

table
  thead
    tr
      th タイトル
      th 著者
      th

  tbody
    - @books.each do |book|
      tr
        td = book.title
        td = book.author
        td = link_to '詳細', book
        td = link_to '編集', edit_book_path(book)
        td = link_to '取消', book, method: :delete, data: { confirm: '本当に削除していいですか？' }
br

= link_to '本を追加', new_book_path

app/views/books/new.html.slim
h1.page-header 書籍の追加

= render 'form'

= link_to '一覧に戻る', books_path

app/views/books/show.html.slim
h1.page-header 書籍情報詳細

p id="notice"
  = notice

= link_to 'Edit', edit_book_path(@book)
'|
= link_to 'Back', books_path

app/views/home/index.html.slim
h1 Welcome to KoreYomo
ul
  li スキマ時間に勉強したいあなたに

= render 'tasks/hot'

app/views/layouts/application.html.slim
doctype 5
html
  head
    title= content_for?(:title) ? yield(:title) : "Koreyomo"
    = csrf_meta_tags

    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    = javascript_include_tag "//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"
    = stylesheet_link_tag href="//netdna.bootstrapcdn.com/bootswatch/3.1.1/cerulean/bootstrap.min.css", media: "all", "data-turbolinks-track" => true
    = stylesheet_link_tag href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css", media: "all", "data-turbolinks-track" => true
    = stylesheet_link_tag href="http://getbootstrap.com/examples/dashboard/dashboard.css", media: "all", "data-turbolinks-track" => true


  body
    - if @current_user
      p
       | ようこそ
       = current_user.name
       = 'さん '
       = link_to 'ログアウト', logout_path
    - else
       = link_to 'ログイン', '/auth/twitter'
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          a.btn.btn-navbar data-target=".nav-collapse" data-toggle="collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.brand href="#"Koreyomo
          .container.nav-collapse
            ul.nav
              li= link_to "Link 1", "/path1"
              li= link_to "Link 2", "/path2"
              li= link_to "Link 3", "/path3"

    .container

      .row
        .span9
          = bootstrap_flash
          = yield
        .span3
          .well.sidebar-nav
            h3 Sidebar
            ul.nav.nav-list
              li.nav-header Sidebar
              li= link_to "Link 1", "/path1"
              li= link_to "Link 2", "/path2"
              li= link_to "Link 3", "/path3"
    
      footer
        p &copy; Company 2014

app/views/tasks/_form.html.slim
= form_for @task do |f|
  - if @task.errors.any?
    #error_explanation
      h2 = "#{pluralize(@task.errors.count, "error")} prohibited this task from being saved:"
      ul
        - @task.errors.full_messages.each do |message|
          li = message

  .field
    ul.list-group
      li.list-group-item.list-group-item-info
          strong タスク名
      li.list-group-item = f.text_field :name
      li.list-group-item.list-group-item-info
        strong タスクサイズ
      li.list-group-item = f.number_field :size
  .actions = f.submit '保存', class: 'btn btn-danger'

app/views/tasks/_hot.html.slim
h3 作業中
- @tasks_wip.each do |task|
  = link_to task_path(task), class: 'btn btn-default' do
    = task.name
    '  (
    = task.progress_point
    '  )
  br
h3 積み
- @tasks_ready.each do |task|
  = link_to task.name, task_path(task), class: 'btn btn-default'
  br

br
= link_to 'タスク一覧へ', tasks_path, class: 'btn btn-default'

app/views/tasks/done.html.slim
h1.page-header 終了タスク一覧

table
  tr
    th タスク名
    th 状態
    th 合計ポイント

  - @tasks.each do |task|
    tr
      td = task.name
      td = task.state_name
      td = task.done_point
br

app/views/tasks/edit.html.slim
h1.page-header タスクを変更

== render 'form'

= link_to '詳細', @task, class: 'btn btn-default'
'　
= link_to '戻る', tasks_path, class: 'btn btn-default'

app/views/tasks/index.html.slim
h1.page-header タスク一覧

table.table.table-striped
  tr
    th タスク名
    th 状態
    th

  - @tasks.each do |task|
    tr
      td = link_to task.name, task
      td = task.state_name
      td = link_to '進捗を登録', increase_point_task_path(task, point: 1), :method => :post
br

= link_to 'タスクを追加', new_task_path, class: 'btn btn-default'

app/views/tasks/new.html.slim
h1.page-header タスクを追加

== render 'form'

= link_to '戻る', tasks_path, class: 'btn btn-default'

app/views/tasks/show.html.slim
h1.page-header タスク詳細

dl data-role="listview"
  dt タスク名
  dd = @task.name
  dt タスクサイズ
  dd = @task.size
  dt タスク状態
  dd = @task.state_name
  - if @task.wip?
    dt 進捗
    dd = @task.progress_point

ul
  li = link_to '進捗を登録', increase_point_task_path(@task, point: 1), class: 'btn btn-default', method: :post

= link_to '編集', edit_task_path(@task), class: 'btn btn-default'
'　
= link_to '戻る', tasks_path, class: 'btn btn-default'